export interface ReserveData {
  id: string
  underlyingAsset: string
  name: string
  symbol: string
  decimals: number
  isActive: boolean
  isFrozen: boolean
  usageAsCollateralEnabled: boolean
  aTokenAddress: string
  stableDebtTokenAddress: string
  variableDebtTokenAddress: string
  borrowingEnabled: boolean
  stableBorrowRateEnabled: boolean
  reserveFactor: string
  baseLTVasCollateral: string
  optimalUtilisationRate: string
  stableRateSlope1: string
  stableRateSlope2: string
  averageStableRate: string
  stableDebtLastUpdateTimestamp: number
  baseVariableBorrowRate: string
  variableRateSlope1: string
  variableRateSlope2: string
  liquidityIndex: string
  reserveLiquidationThreshold: string
  reserveLiquidationBonus: string
  variableBorrowIndex: string
  variableBorrowRate: string
  availableLiquidity: string
  stableBorrowRate: string
  liquidityRate: string
  totalPrincipalStableDebt: string
  totalScaledVariableDebt: string
  lastUpdateTimestamp: number
  price: {
    priceInEth: string
  }
  aEmissionPerSecond: string
  vEmissionPerSecond: string
  sEmissionPerSecond: string
  aIncentivesLastUpdateTimestamp: number
  vIncentivesLastUpdateTimestamp: number
  sIncentivesLastUpdateTimestamp: number
  aTokenIncentivesIndex: string
  vTokenIncentivesIndex: string
  sTokenIncentivesIndex: string
}
