/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  GhoDiscountRateStrategy,
  GhoDiscountRateStrategyInterface,
} from "./GhoDiscountRateStrategy";

const _abi = [
  {
    inputs: [],
    name: "DISCOUNT_RATE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DISCOUNT_TOKEN",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GHO_DISCOUNTED_PER_DISCOUNT_TOKEN",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_DEBT_TOKEN_BALANCE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_DISCOUNT_TOKEN_BALANCE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "debtBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "discountTokenBalance",
        type: "uint256",
      },
    ],
    name: "calculateDiscountRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102c1806100206000396000f3fe608060405234801561001057600080fd5b50600436106100725760003560e01c806393adbec51161005057806393adbec5146100e957806398c4f438146100bc578063b510c589146100fc57600080fd5b80631fd5c9e9146100775780633454274e146100bc578063771a73af146100d9575b600080fd5b610092734da27a545c0c5b758a6ba100e3a049001de870f581565b60405173ffffffffffffffffffffffffffffffffffffffff90911681526020015b60405180910390f35b6100cb670de0b6b3a764000081565b6040519081526020016100b3565b6100cb68056bc75e2d6310000081565b6100cb6100f73660046101ca565b610105565b6100cb6107d081565b6000670de0b6b3a76400008210806101245750670de0b6b3a764000083105b1561013157506000610175565b60006101468368056bc75e2d6310000061017b565b905083811061015a576107d0915050610175565b836101676107d0836101ec565b6101719190610250565b9150505b92915050565b600081157ffffffffffffffffffffffffffffffffffffffffffffffffff90fa4a62c4dffff839004841115176101b057600080fd5b50670de0b6b3a764000091026706f05b59d3b20000010490565b600080604083850312156101dd57600080fd5b50508035926020909101359150565b6000817fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff048311821515161561024b577f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b500290565b600082610286577f4e487b7100000000000000000000000000000000000000000000000000000000600052601260045260246000fd5b50049056fea26469706673582212206bbf29bf6be38a8be7683b6b85fad0e89ba775122d079836285e8ed847f2d92564736f6c634300080a0033";

type GhoDiscountRateStrategyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GhoDiscountRateStrategyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GhoDiscountRateStrategy__factory extends ContractFactory {
  constructor(...args: GhoDiscountRateStrategyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<GhoDiscountRateStrategy> {
    return super.deploy(overrides || {}) as Promise<GhoDiscountRateStrategy>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): GhoDiscountRateStrategy {
    return super.attach(address) as GhoDiscountRateStrategy;
  }
  override connect(signer: Signer): GhoDiscountRateStrategy__factory {
    return super.connect(signer) as GhoDiscountRateStrategy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GhoDiscountRateStrategyInterface {
    return new utils.Interface(_abi) as GhoDiscountRateStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GhoDiscountRateStrategy {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as GhoDiscountRateStrategy;
  }
}
