/* Autogenerated file. Do not edit manually. */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type {
  VotingMachineDataHelper,
  VotingMachineDataHelperInterface,
} from '../VotingMachineDataHelper';

const _abi = [
  {
    inputs: [
      {
        internalType: 'contract IVotingMachineWithProofs',
        name: 'votingMachine',
        type: 'address',
      },
      {
        components: [
          {
            internalType: 'uint256',
            name: 'id',
            type: 'uint256',
          },
          {
            internalType: 'bytes32',
            name: 'snapshotBlockHash',
            type: 'bytes32',
          },
        ],
        internalType: 'struct IVotingMachineDataHelper.InitialProposal[]',
        name: 'initialProposals',
        type: 'tuple[]',
      },
      {
        internalType: 'address',
        name: 'user',
        type: 'address',
      },
    ],
    name: 'getProposalsData',
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: 'uint256',
                name: 'id',
                type: 'uint256',
              },
              {
                internalType: 'bool',
                name: 'sentToGovernance',
                type: 'bool',
              },
              {
                internalType: 'uint40',
                name: 'startTime',
                type: 'uint40',
              },
              {
                internalType: 'uint40',
                name: 'endTime',
                type: 'uint40',
              },
              {
                internalType: 'uint40',
                name: 'votingClosedAndSentTimestamp',
                type: 'uint40',
              },
              {
                internalType: 'uint128',
                name: 'forVotes',
                type: 'uint128',
              },
              {
                internalType: 'uint128',
                name: 'againstVotes',
                type: 'uint128',
              },
              {
                internalType: 'uint256',
                name: 'creationBlockNumber',
                type: 'uint256',
              },
              {
                internalType: 'uint256',
                name: 'votingClosedAndSentBlockNumber',
                type: 'uint256',
              },
            ],
            internalType:
              'struct IVotingMachineWithProofs.ProposalWithoutVotes',
            name: 'proposalData',
            type: 'tuple',
          },
          {
            components: [
              {
                internalType: 'bool',
                name: 'support',
                type: 'bool',
              },
              {
                internalType: 'uint248',
                name: 'votingPower',
                type: 'uint248',
              },
            ],
            internalType: 'struct IVotingMachineDataHelper.VotedInfo',
            name: 'votedInfo',
            type: 'tuple',
          },
          {
            internalType: 'contract IVotingStrategy',
            name: 'strategy',
            type: 'address',
          },
          {
            internalType: 'contract IDataWarehouse',
            name: 'dataWarehouse',
            type: 'address',
          },
          {
            internalType: 'address[]',
            name: 'votingAssets',
            type: 'address[]',
          },
          {
            internalType: 'bool',
            name: 'hasRequiredRoots',
            type: 'bool',
          },
          {
            components: [
              {
                internalType: 'uint24',
                name: 'votingDuration',
                type: 'uint24',
              },
              {
                internalType: 'bytes32',
                name: 'l1ProposalBlockHash',
                type: 'bytes32',
              },
            ],
            internalType:
              'struct IVotingMachineWithProofs.ProposalVoteConfiguration',
            name: 'voteConfig',
            type: 'tuple',
          },
          {
            internalType: 'enum IVotingMachineWithProofs.ProposalState',
            name: 'state',
            type: 'uint8',
          },
        ],
        internalType: 'struct IVotingMachineDataHelper.Proposal[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class VotingMachineDataHelper__factory {
  static readonly abi = _abi;
  static createInterface(): VotingMachineDataHelperInterface {
    return new utils.Interface(_abi) as VotingMachineDataHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): VotingMachineDataHelper {
    return new Contract(
      address,
      _abi,
      signerOrProvider,
    ) as VotingMachineDataHelper;
  }
}
