name: Build PR From Fork

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: | # check if PR opened from fork
      github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
        with:
          persist-credentials: false

      - name: Build packages
        uses: ./.github/actions/build


      - name: Save SHA of commit
        if: github.event.number 
        shell: sh
        run: |
          mkdir -p ./__pr
          echo ${{ github.event.pull_request.head.sha }} > ./__pr/SHA
          echo ${{ github.event.number }} > ./__pr/NUM
      - name: store PR info
        if: github.event.number 
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v3.0.0
        with:
          name: pr
          path: __pr/
          retention-days: 10
      - name: Store math-utils build
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v3.0.0
        with:
          name: math-utils
          path: packages/math-utils/dist
          retention-days: 10
      - name: Store contract-helpers build
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v3.0.0
        with:
          name: contract-helpers
          path: packages/contract-helpers/dist
          retention-days: 10
