name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  ci:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.head.repo.full_name == github.repository ||
      (github.ref == 'refs/heads/master' && github.event_name == 'push')
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
        with:
          token: '${{ secrets.BOT_TOKEN }}'

      - name: Build packages
        uses: ./.github/actions/build

      - name: prepare npm access
        run: echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}' >> ~/.npmrc
      # https://github.com/lerna/lerna/issues/2788 --no-verify-access
      # https://github.com/lerna/lerna/issues/1893 --preid ${{ github.sha }}
      - name: prerelease
        if: |
          !contains(github.head_ref, 'dependabot') &&
          github.ref != 'refs/heads/master'
        run: |
          yarn release:canary \
          --yes --no-verify-access \
          --dist-tag '${{ github.event.pull_request.head.sha }}' --preid '${{ github.event.pull_request.head.sha }}' \
          | tee __publish-log.txt

      - name: Comment on PR
        if: github.event.number
        uses: ./.github/actions/pr-comment
        with:
          PR_NUMBER: '${{ github.event.number }}'

      - name: release
        if: |
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master'
        env:
          GH_TOKEN: '${{ secrets.BOT_TOKEN }}'
        run: |
          git config user.name "GitHub Actions Build"
          git config user.email "developers@aave.com"
          yarn release:check
          yarn release:latest --yes --no-verify-access
